export interface Reporte{
    ID:number;
    createdAt:string;
    intpro_DESCRIPCION:string;
    intpro_ABREV:string;
    intrp_NUMEROPROCESO:string;
    intrp_CODIGOPROCESO:string;
    intrp_DETALLE:string;
    intres_DETALLE:string;
    intrp_NUMOFICIO:string;
    intrp_NUMCONTRATO:string;
    intrp_VALORCONT:number;
    ma_CONT_RAZON_SOCIAL:string;
    contraf_NUMERO_CONTRATO:string;
    contraf_VALOR_CONTRATO:number;
    intdep_CODIGO:string;
    intdep_DESCRIPCION:string;
    intrp_ANIO:number;
}